version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Src/API/Server/Dockerfile
    environment:
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://server.dashboard:18889
    networks:
    - otel

  server.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
    - 18888:18888
    networks:
    - otel

networks:
  otel: 

